workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
    - when: never

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - sudo /usr/local/bin/owncord-deploy.sh "$CI_PROJECT_DIR"
